<a href="https://colab.research.google.com/github/AtrCheema/Miscellaneous_DL_Tutorials/blob/master/understanding_TimeDistributedLayer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# simple `Conv1D`

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, TimeDistributed, Conv1D, LSTM, MaxPool1D
import numpy as np

def reset_seed(seed=313):
    tf.keras.backend.clear_session()
    tf.random.set_seed(seed)
    np.random.seed(seed)

np.set_printoptions(linewidth=150)

print(tf.__version__, np.__version__)

2.3.0 1.18.5


In [ ]:
input_features = 3
lookback = 6
batch_size=2
input_shape = lookback,input_features
ins = Input(shape=input_shape, name='my_input')
outs = Conv1D(filters=8, kernel_size=3,
              strides=1, padding='same', kernel_initializer='ones',
              name='my_conv1d')(ins)
model = Model(inputs=ins, outputs=outs)

input_array = np.arange(36).reshape((batch_size, *input_shape))
conv1d_weights = model.get_layer('my_conv1d').weights[0].numpy() 
output_array = model.predict(input_array)

In [ ]:
input_array, input_array.shape

(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]]), (2, 6, 3))

In [ ]:
conv1d_weights, conv1d_weights.shape

(array([[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],
 
        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],
 
        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]]], dtype=float32), (3, 3, 8))

In [ ]:
output_array, output_array.shape

(array([[[ 15.,  15.,  15.,  15.,  15.,  15.,  15.,  15.],
         [ 36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.],
         [ 63.,  63.,  63.,  63.,  63.,  63.,  63.,  63.],
         [ 90.,  90.,  90.,  90.,  90.,  90.,  90.,  90.],
         [117., 117., 117., 117., 117., 117., 117., 117.],
         [ 87.,  87.,  87.,  87.,  87.,  87.,  87.,  87.]],
 
        [[123., 123., 123., 123., 123., 123., 123., 123.],
         [198., 198., 198., 198., 198., 198., 198., 198.],
         [225., 225., 225., 225., 225., 225., 225., 225.],
         [252., 252., 252., 252., 252., 252., 252., 252.],
         [279., 279., 279., 279., 279., 279., 279., 279.],
         [195., 195., 195., 195., 195., 195., 195., 195.]]], dtype=float32),
 (2, 6, 8))

# multiple inputs multiple layers

In [ ]:

input_features = 3
lookback = 3
batch_size=2
input_shape = lookback,input_features
ins1 = Input(shape=input_shape, name='my_input1')
ins2 = Input(shape=input_shape, name='my_input2')
outs1 = Conv1D(filters=8, kernel_size=3,
              strides=1, padding='same', kernel_initializer='ones',
              name='my_conv1d1')(ins1)
outs2 = Conv1D(filters=8, kernel_size=3,
              strides=1, padding='same', kernel_initializer='ones',
              name='my_conv1d2')(ins2)
model = Model(inputs=[ins1, ins2], outputs=[outs1, outs2])

sub_seq = 2
input_shape = sub_seq, 3, input_features
input_array = np.arange(36).reshape((batch_size, *input_shape))
input_array1 = input_array[:, 0, :, :]
input_array2 = input_array[:, 1, :, :]

conv1d1_weights = model.get_layer('my_conv1d1').weights[0].numpy()
conv1d2_weights = model.get_layer('my_conv1d2').weights[0].numpy()
output_array = model.predict([input_array1, input_array2])

In [ ]:
print(input_array1, '\n\n', input_array2)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 

 [[[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]]


In [ ]:
conv1d2_weights, conv1d2_weights

(array([[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],
 
        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],
 
        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]]], dtype=float32),
 array([[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],
 
        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],
 
        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]]], dtype=float32))

In [ ]:
output_array

[array([[[ 15.,  15.,  15.,  15.,  15.,  15.,  15.,  15.],
         [ 36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.],
         [ 33.,  33.,  33.,  33.,  33.,  33.,  33.,  33.]],
 
        [[123., 123., 123., 123., 123., 123., 123., 123.],
         [198., 198., 198., 198., 198., 198., 198., 198.],
         [141., 141., 141., 141., 141., 141., 141., 141.]]], dtype=float32),
 array([[[ 69.,  69.,  69.,  69.,  69.,  69.,  69.,  69.],
         [117., 117., 117., 117., 117., 117., 117., 117.],
         [ 87.,  87.,  87.,  87.,  87.,  87.,  87.,  87.]],
 
        [[177., 177., 177., 177., 177., 177., 177., 177.],
         [279., 279., 279., 279., 279., 279., 279., 279.],
         [195., 195., 195., 195., 195., 195., 195., 195.]]], dtype=float32)]

# multiple inputs shared layer

In [ ]:

input_features = 3
lookback = 6
sub_seq = 2
input_shape = sub_seq, 3, input_features
batch_size = 2

ins = Input(shape=input_shape, name='my_input')
conv = Conv1D(filters=8, kernel_size=3,
              strides=1, padding='same',
              kernel_initializer='ones', name='my_conv1d')

conv1_out = conv(ins[:, 0, :, :])
conv2_out = conv(ins[:, 1, :, :])
model = Model(inputs=ins, outputs=[conv1_out, conv2_out])

input_array = np.arange(36).reshape((batch_size, *input_shape))
conv1d_weights = model.get_layer('my_conv1d').weights[0].numpy()
output_array = model.predict(input_array)

In [ ]:
input_array

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]],

        [[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]]])

In [ ]:
conv1d_weights

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]], dtype=float32)

In [ ]:
output_array[0]

array([[[ 15.,  15.,  15.,  15.,  15.,  15.,  15.,  15.],
        [ 36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.],
        [ 33.,  33.,  33.,  33.,  33.,  33.,  33.,  33.]],

       [[123., 123., 123., 123., 123., 123., 123., 123.],
        [198., 198., 198., 198., 198., 198., 198., 198.],
        [141., 141., 141., 141., 141., 141., 141., 141.]]], dtype=float32)

In [ ]:
output_array[1]

array([[[ 69.,  69.,  69.,  69.,  69.,  69.,  69.,  69.],
        [117., 117., 117., 117., 117., 117., 117., 117.],
        [ 87.,  87.,  87.,  87.,  87.,  87.,  87.,  87.]],

       [[177., 177., 177., 177., 177., 177., 177., 177.],
        [279., 279., 279., 279., 279., 279., 279., 279.],
        [195., 195., 195., 195., 195., 195., 195., 195.]]], dtype=float32)

# `TimeDistributed Conv1D`

In [ ]:

input_features = 3
lookback = 6
sub_seq = 2
input_shape = sub_seq, 3, input_features
batch_size = 2

ins = Input(shape=input_shape, name='my_input')
outs = TimeDistributed(Conv1D(filters=8, kernel_size=3,
              strides=1, padding='same', kernel_initializer='ones', 
              name='my_conv1d'))(ins)
model = Model(inputs=ins, outputs=outs)

input_array = np.arange(36).reshape((batch_size, *input_shape))
output_array = model.predict(input_array)

In [ ]:
input_array

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]],

        [[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]]])

In [ ]:
output_array

array([[[[ 15.,  15.,  15.,  15.,  15.,  15.,  15.,  15.],
         [ 36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.],
         [ 33.,  33.,  33.,  33.,  33.,  33.,  33.,  33.]],

        [[ 69.,  69.,  69.,  69.,  69.,  69.,  69.,  69.],
         [117., 117., 117., 117., 117., 117., 117., 117.],
         [ 87.,  87.,  87.,  87.,  87.,  87.,  87.,  87.]]],


       [[[123., 123., 123., 123., 123., 123., 123., 123.],
         [198., 198., 198., 198., 198., 198., 198., 198.],
         [141., 141., 141., 141., 141., 141., 141., 141.]],

        [[177., 177., 177., 177., 177., 177., 177., 177.],
         [279., 279., 279., 279., 279., 279., 279., 279.],
         [195., 195., 195., 195., 195., 195., 195., 195.]]]], dtype=float32)

So `TimeDistributed` Just applies same `Conv1D` to each sub-sequence/incoming input.

# `TimeDistributed` `LSTM`

In [ ]:

tf.random.set_seed(313) 

input_features = 3
sub_seq = 2
input_shape = sub_seq, 3, input_features
batch_size = 2

ins = Input(shape=input_shape, name='my_input')
outs = TimeDistributed(LSTM(units=8, name='my_lstm'))(ins)
model = Model(inputs=ins, outputs=outs)

input_array = np.arange(36).reshape((batch_size, *input_shape))
output_array = model.predict(input_array)

In [ ]:
input_array

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]],

        [[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]]])

In [ ]:
output_array[:, 0, :]

array([[-1.6062409e-01,  2.2913465e-01,  1.0585530e-01,  6.0561293e-01, -3.6559592e-03, -1.4262524e-01,  9.5918020e-03,  2.6522632e-04],
       [-1.3387868e-03,  1.6973073e-02,  1.3584232e-02,  2.4525641e-01, -5.3840652e-09, -1.3385731e-03,  9.8304715e-09,  1.6285184e-13]],
      dtype=float32)

In [ ]:
output_array[:, 1, :]

array([[-1.6962688e-02,  6.4336620e-02,  6.8063535e-02,  5.8035445e-01, -4.6160312e-06, -1.3993834e-02,  1.5005664e-05,  6.2304650e-09],
       [-1.0763946e-04,  4.2649782e-03,  2.5343844e-03,  8.0139175e-02, -6.2821484e-12, -1.3424609e-04,  5.9522946e-12,  4.1778258e-18]],
      dtype=float32)

# manual weight sharing of `LSTM`

In [ ]:

tf.random.set_seed(313) 

input_features = 3
sub_seq = 2
input_shape = sub_seq, 3, input_features
batch_size = 2

ins = Input(shape=input_shape, name='my_input')
lstm = LSTM(units=8, name='my_lstm')

lstm1_out = lstm(ins[:, 0, :, :])
lstm2_out = lstm(ins[:, 1, :, :])
model = Model(inputs=ins, outputs=[lstm1_out, lstm2_out])

input_array = np.arange(36).reshape((batch_size, *input_shape))
output_array = model.predict(input_array)

In [ ]:
input_array

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]],

        [[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]]])

In [ ]:
output_array[0]

array([[-1.6062410e-01,  2.2913465e-01,  1.0585530e-01,  6.0561293e-01, -3.6559592e-03, -1.4262524e-01,  9.5918020e-03,  2.6522632e-04],
       [-1.3387636e-03,  1.6973050e-02,  1.3584232e-02,  2.4525636e-01, -5.3840639e-09, -1.3385731e-03,  9.8304707e-09,  1.6285168e-13]],
      dtype=float32)

In [ ]:
output_array[1]

array([[-1.6962737e-02,  6.4336628e-02,  6.8063594e-02,  5.8035445e-01, -4.6160267e-06, -1.3993834e-02,  1.5005662e-05,  6.2304650e-09],
       [-1.0763946e-04,  4.2649782e-03,  2.5344139e-03,  8.0139175e-02, -6.2821367e-12, -1.3424607e-04,  5.9522842e-12,  4.1778180e-18]],
      dtype=float32)

# Curious case of `Dense`

In [ ]:

tf.random.set_seed(313)

input_features = 3
lookback = 6
batch_size=2
input_shape = lookback,input_features

input_shape = lookback, input_features
ins = Input(input_shape, name='my_input')
out = Dense(units=5,  name='my_output')(ins)
model = Model(inputs=ins, outputs=out)

input_array = np.arange(36).reshape(batch_size, *input_shape)
output_array = model.predict(input_array)

In [ ]:
input_array, input_array.shape

(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]]), (2, 6, 3))

In [ ]:
output_array, output_array.shape

(array([[[  0.27596885,   0.70854443,  -0.53744566,  -0.70061463,  -0.20640421],
         [  0.36203665,   3.999878  ,  -1.7514435 ,  -2.695434  ,   0.17058378],
         [  0.44810438,   7.291211  ,  -2.9654412 ,  -4.6902533 ,   0.5475718 ],
         [  0.53417236,  10.582545  ,  -4.179439  ,  -6.685073  ,   0.92456   ],
         [  0.62023985,  13.8738785 ,  -5.393437  ,  -8.679893  ,   1.3015479 ],
         [  0.7063078 ,  17.165213  ,  -6.607435  , -10.674712  ,   1.6785362 ]],
 
        [[  0.7923758 ,  20.456545  ,  -7.821433  , -12.669531  ,   2.055524  ],
         [  0.8784433 ,  23.747879  ,  -9.035431  , -14.664351  ,   2.432512  ],
         [  0.9645113 ,  27.039211  , -10.249429  , -16.65917   ,   2.8094997 ],
         [  1.0505788 ,  30.330545  , -11.463427  , -18.65399   ,   3.1864882 ],
         [  1.1366472 ,  33.62188   , -12.6774235 , -20.64881   ,   3.5634766 ],
         [  1.2227151 ,  36.91321   , -13.891422  , -22.64363   ,   3.9404645 ]]], dtype=float32),
 (2, 6,

In [ ]:

tf.random.set_seed(313)

input_features = 3
lookback = 6
sub_seq = 2
input_shape = sub_seq, 3, input_features
batch_size = 2

ins = Input(input_shape, name='my_input')
out = TimeDistributed(Dense(units=5, name='my_output'))(ins)
model = Model(inputs=ins, outputs=out)


input_array = np.arange(36).reshape(batch_size, *input_shape)
output_array = model.predict(input_array)

In [ ]:
input_array, input_array.shape

(array([[[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]],
 
         [[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]]],
 
 
        [[[18, 19, 20],
          [21, 22, 23],
          [24, 25, 26]],
 
         [[27, 28, 29],
          [30, 31, 32],
          [33, 34, 35]]]]), (2, 2, 3, 3))

In [ ]:
output_array, output_array.shape

(array([[[[  0.27596885,   0.70854443,  -0.53744566,  -0.70061463,  -0.20640421],
          [  0.36203665,   3.999878  ,  -1.7514435 ,  -2.695434  ,   0.17058378],
          [  0.44810438,   7.291211  ,  -2.9654412 ,  -4.6902533 ,   0.5475718 ]],
 
         [[  0.53417236,  10.582545  ,  -4.179439  ,  -6.685073  ,   0.92456   ],
          [  0.62023985,  13.8738785 ,  -5.393437  ,  -8.679893  ,   1.3015479 ],
          [  0.7063078 ,  17.165213  ,  -6.607435  , -10.674712  ,   1.6785362 ]]],
 
 
        [[[  0.7923758 ,  20.456545  ,  -7.821433  , -12.669531  ,   2.055524  ],
          [  0.8784433 ,  23.747879  ,  -9.035431  , -14.664351  ,   2.432512  ],
          [  0.9645113 ,  27.039211  , -10.249429  , -16.65917   ,   2.8094997 ]],
 
         [[  1.0505788 ,  30.330545  , -11.463427  , -18.65399   ,   3.1864882 ],
          [  1.1366472 ,  33.62188   , -12.6774235 , -20.64881   ,   3.5634766 ],
          [  1.2227151 ,  36.91321   , -13.891422  , -22.64363   ,   3.9404645 ]]]], d

so far looks very similar to `TimeDistributed(Conv1D)` or `TimeDistributed(LSTM)`.


In [ ]:

tf.random.set_seed(313)

input_features = 3
lookback = 6
input_shape = lookback, input_features
batch_size = 2

ins = Input(input_shape, name='my_input')
out = TimeDistributed(Dense(5, use_bias=False, name='my_output'))(ins)
model = Model(inputs=ins, outputs=out)

input_array = np.arange(36).reshape(batch_size, *input_shape)
output_array = model.predict(input_array)

In [ ]:
input_array, input_array.shape

(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]]), (2, 6, 3))

In [ ]:
output_array, output_array.shape

(array([[[  0.27596885,   0.70854443,  -0.53744566,  -0.70061463,  -0.20640421],
         [  0.36203665,   3.999878  ,  -1.7514435 ,  -2.695434  ,   0.17058378],
         [  0.44810438,   7.291211  ,  -2.9654412 ,  -4.6902533 ,   0.5475718 ],
         [  0.53417236,  10.582545  ,  -4.179439  ,  -6.685073  ,   0.92456   ],
         [  0.62023985,  13.8738785 ,  -5.393437  ,  -8.679893  ,   1.3015479 ],
         [  0.7063078 ,  17.165213  ,  -6.607435  , -10.674712  ,   1.6785362 ]],
 
        [[  0.7923758 ,  20.456545  ,  -7.821433  , -12.669531  ,   2.055524  ],
         [  0.8784433 ,  23.747879  ,  -9.035431  , -14.664351  ,   2.432512  ],
         [  0.9645113 ,  27.039211  , -10.249429  , -16.65917   ,   2.8094997 ],
         [  1.0505788 ,  30.330545  , -11.463427  , -18.65399   ,   3.1864882 ],
         [  1.1366472 ,  33.62188   , -12.6774235 , -20.64881   ,   3.5634766 ],
         [  1.2227151 ,  36.91321   , -13.891422  , -22.64363   ,   3.9404645 ]]], dtype=float32),
 (2, 6,

So whether we we `TimeDistributed(Dense)` or `Dense`, they are actually equivalent.

What if we try same with `Conv1D` or `LSTM` i.e. wrapping these layers in `TimeDistributed` without modifying/dividing input into sub-sequences?

In [ ]:

input_features = 3
lookback = 6
input_shape = lookback, input_features
ins = Input(shape=(lookback, input_features), name='my_input')
outs = TimeDistributed(Conv1D(filters=8, kernel_size=3,
              strides=1, padding='valid', kernel_initializer='ones',
              name='my_conv1d'))(ins)
model = Model(inputs=ins, outputs=outs)

input_array = np.arange(36).reshape((batch_size, *input_shape))


ValueError: ignored

The above error message can be slightly confusing or atleast can be resolved in a wrong manner as we do in following case;

In [ ]:

input_features = 3
lookback = 6
input_shape = lookback, input_features
ins = Input(shape=(batch_size, lookback, input_features), name='my_input')
outs = TimeDistributed(Conv1D(filters=8, kernel_size=3,
              strides=1, padding='valid', kernel_initializer='ones', 
              name='my_conv1d'))(ins)
model = Model(inputs=ins, outputs=outs)

input_array = np.arange(36).reshape((batch_size, *input_shape))
print(input_array.shape)

(2, 6, 3)


So we are able to compile the model, although it is wrong. 

In [ ]:
output_array = model.predict(input_array)
print(output_array.shape)

ValueError: ignored

This error message is exactly related to `TimeDistributed` layer. The `TimeDistributed` layer here expects input having 4 dimensions, 1st being batch size, second being the sub-sequences, 3rd being the time-steps or whatever and 4rth being number of input features here. 

Anyhow, the conclusion is, we can't just wrap layers in `TimeDistributed` except for `Dense` layer. Hence, using `TimeDistributed(Dense)` does not make any sense (to me until version 2.3.0).



# More than just weight sharing

`TimeDistributed` layer is meant to provide more functionality than just weight sharing. We see, pooling layers or flatten layers wrapped into `TimeDistributed` layer even though pooling layers or flattening layers don't have any weights. This is because if we have applied `TimeDistributed(Conv1D)`, this will sprout output for each sub-sequence. We would naturally like to apply pooling and consequently flattening layers to each output fo the sub-sequences.

In [ ]:

input_features = 3
sub_seq = 2
input_shape = sub_seq, 3, input_features
batch_size = 2

ins = Input(shape=input_shape, name='my_input')
conv_outs = TimeDistributed(Conv1D(filters=8, kernel_size=3,
              strides=1,
              padding='same',
              kernel_initializer='ones', 
              name='my_conv1d'))(ins)
outs = TimeDistributed(MaxPool1D(pool_size=2))(conv_outs)
model = Model(inputs=ins, outputs=[outs, conv_outs])

input_array = np.arange(36).reshape((batch_size, *input_shape))
output_array, conv_output = model.predict(input_array)

In [ ]:
print(input_array.shape)
input_array

(2, 2, 3, 3)


array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]],

        [[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]]])

In [ ]:
conv_output, conv_output.shape

(array([[[[ 15.,  15.,  15.,  15.,  15.,  15.,  15.,  15.],
          [ 36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.],
          [ 33.,  33.,  33.,  33.,  33.,  33.,  33.,  33.]],
 
         [[ 69.,  69.,  69.,  69.,  69.,  69.,  69.,  69.],
          [117., 117., 117., 117., 117., 117., 117., 117.],
          [ 87.,  87.,  87.,  87.,  87.,  87.,  87.,  87.]]],
 
 
        [[[123., 123., 123., 123., 123., 123., 123., 123.],
          [198., 198., 198., 198., 198., 198., 198., 198.],
          [141., 141., 141., 141., 141., 141., 141., 141.]],
 
         [[177., 177., 177., 177., 177., 177., 177., 177.],
          [279., 279., 279., 279., 279., 279., 279., 279.],
          [195., 195., 195., 195., 195., 195., 195., 195.]]]], dtype=float32),
 (2, 2, 3, 8))

In [ ]:
output_array, output_array.shape

(array([[[[ 36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.]],
 
         [[117., 117., 117., 117., 117., 117., 117., 117.]]],
 
 
        [[[198., 198., 198., 198., 198., 198., 198., 198.]],
 
         [[279., 279., 279., 279., 279., 279., 279., 279.]]]], dtype=float32),
 (2, 2, 1, 8))

In [ ]:

input_features = 3
sub_seq = 2
input_shape = sub_seq, 3, input_features
batch_size = 2

ins = Input(shape=input_shape, name='my_input')
conv_outs = TimeDistributed(Conv1D(filters=8, kernel_size=3,
              strides=1, padding='same',
              kernel_initializer='ones', 
              name='my_conv1d'))(ins)
outs = TimeDistributed(MaxPool1D(pool_size=2, padding='same'))(conv_outs)
model = Model(inputs=ins, outputs=outs)

input_array = np.arange(36).reshape((batch_size, *input_shape))
output_array = model.predict(input_array) 

In [ ]:
input_array, input_array.shape

(array([[[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]],
 
         [[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]]],
 
 
        [[[18, 19, 20],
          [21, 22, 23],
          [24, 25, 26]],
 
         [[27, 28, 29],
          [30, 31, 32],
          [33, 34, 35]]]]), (2, 2, 3, 3))

In [ ]:
output_array, output_array.shape

(array([[[[ 36.,  36.,  36.,  36.,  36.,  36.,  36.,  36.],
          [ 33.,  33.,  33.,  33.,  33.,  33.,  33.,  33.]],
 
         [[117., 117., 117., 117., 117., 117., 117., 117.],
          [ 87.,  87.,  87.,  87.,  87.,  87.,  87.,  87.]]],
 
 
        [[[198., 198., 198., 198., 198., 198., 198., 198.],
          [141., 141., 141., 141., 141., 141., 141., 141.]],
 
         [[279., 279., 279., 279., 279., 279., 279., 279.],
          [195., 195., 195., 195., 195., 195., 195., 195.]]]], dtype=float32),
 (2, 2, 2, 8))